import { CareerModel, ImageModel } from "@models/core";
import { InstructorModel, CatalogueModel, TechniqueRequisite,CourseProfileModel } from "@models/cecy";
export interface CourseModel {
  id?: number;
  academicPeriod?: CatalogueModel;
  area?: CatalogueModel;
  career?: CareerModel;
  category?: CatalogueModel;
  certifiedType?: CatalogueModel;
  complianceIndicator?: CatalogueModel;
  control?: CatalogueModel;
  courseType?: CatalogueModel;
  entityCertification?: CatalogueModel;
  formationType?: CatalogueModel;
  frequency?: CatalogueModel;
  meanVerification?: CatalogueModel;
  modality?: CatalogueModel;
  responsible?: InstructorModel;
  speciality?: CatalogueModel;
  state?: CatalogueModel;
  images?: ImageModel[];
  abbreviation?: string;
  alignment?: string;
  approvedAt?: Date;
  bibliographies?: string[];
  code?: string;
  cost?: number;
  duration?: number;
  evaluationMechanisms?: string;
  expiredAt?: Date;
  free?: boolean;
  name?: string;
  needs?: string[];
  neededAt?: string;
  recordNumber?: string;
  learningEnvironments?: string[];
  localProposal?: string;
  objective?: string;
  observation?: string;
  participantTypes?: CatalogueModel[];
  practiceHours?: number;
  proposedAt?: string;
  project?: string;
  requiredInstallingSources?: string[];
  setecName?: string;
  summary?: string;
  targetGroups?: string[];
  teachingStrategies?: string[];
  techniquesRequisites?: TechniqueRequisite;
  theoryHours?: number;
  createdAt?: Date;
  updatedAt?: Date;
  profilecourse?:CourseProfileModel;
}
